from PyQt5 import QtCore
from PyQt5 import QtGui
from PyQt5 import QtWidgets
import numpy


class CapturePanel(QtWidgets.QFrame):

    def setupUi(self, qframe):
        row, col, space_available = self._get_row_col(qframe)
        suffix = "_" + str(2 * col + row)

        self.frme_cap_panel_0 = QtWidgets.QFrame(qframe)
        self.frme_cap_panel_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_cap_panel_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_cap_panel_0.setLineWidth(1)
        self.frme_cap_panel_0.setObjectName("frme_cap_panel" + suffix)
        self.layout_hrz_frme_cap_panel_0 = QtWidgets.QHBoxLayout(self.frme_cap_panel_0)
        self.layout_hrz_frme_cap_panel_0.setContentsMargins(0, 0, 0, 0)
        self.layout_hrz_frme_cap_panel_0.setSpacing(0)
        self.layout_hrz_frme_cap_panel_0.setObjectName("layout_hrz_frme_cap_panel" + suffix)
        self.frme_cap_controls_0 = QtWidgets.QFrame(self.frme_cap_panel_0)
        self.frme_cap_controls_0.setMaximumSize(QtCore.QSize(80, 16777215))
        self.frme_cap_controls_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_cap_controls_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_cap_controls_0.setObjectName("frme_cap_controls" + suffix)
        self.layout_vrt_frme_cap_controls_0 = QtWidgets.QVBoxLayout(self.frme_cap_controls_0)
        self.layout_vrt_frme_cap_controls_0.setContentsMargins(0, 0, 0, 0)
        self.layout_vrt_frme_cap_controls_0.setSpacing(0)
        self.layout_vrt_frme_cap_controls_0.setObjectName("layout_vrt_frme_cap_controls" + suffix)
        self.frme_zoom_0 = QtWidgets.QFrame(self.frme_cap_controls_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frme_zoom_0.sizePolicy().hasHeightForWidth())
        self.frme_zoom_0.setSizePolicy(sizePolicy)
        self.frme_zoom_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_zoom_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_zoom_0.setObjectName("frme_zoom" + suffix)
        self.layout_hrz_frme_zoom_0 = QtWidgets.QHBoxLayout(self.frme_zoom_0)
        self.layout_hrz_frme_zoom_0.setContentsMargins(3, 3, 0, 3)
        self.layout_hrz_frme_zoom_0.setSpacing(3)
        self.layout_hrz_frme_zoom_0.setObjectName("layout_hrz_frme_zoom" + suffix)
        self.lbl_static_zoom_0 = QtWidgets.QLabel(self.frme_zoom_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_static_zoom_0.sizePolicy().hasHeightForWidth())
        self.lbl_static_zoom_0.setSizePolicy(sizePolicy)
        self.lbl_static_zoom_0.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_static_zoom_0.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_static_zoom_0.setObjectName("lbl_static_zoom" + suffix)
        self.layout_hrz_frme_zoom_0.addWidget(self.lbl_static_zoom_0)
        self.spbx_dbl_zoom_0 = QtWidgets.QDoubleSpinBox(self.frme_zoom_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbx_dbl_zoom_0.sizePolicy().hasHeightForWidth())
        self.spbx_dbl_zoom_0.setSizePolicy(sizePolicy)
        self.spbx_dbl_zoom_0.setMaximumSize(QtCore.QSize(1000, 20))
        self.spbx_dbl_zoom_0.setDecimals(2)
        self.spbx_dbl_zoom_0.setMinimum(0.01)
        self.spbx_dbl_zoom_0.setMaximum(3.0)
        self.spbx_dbl_zoom_0.setSingleStep(0.1)
        self.spbx_dbl_zoom_0.setProperty("value", 1.0)
        self.spbx_dbl_zoom_0.setObjectName("spbx_dbl_zoom" + suffix)
        self.layout_hrz_frme_zoom_0.addWidget(self.spbx_dbl_zoom_0)
        self.layout_vrt_frme_cap_controls_0.addWidget(self.frme_zoom_0)
        self.frme_pause_0 = QtWidgets.QFrame(self.frme_cap_controls_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frme_pause_0.sizePolicy().hasHeightForWidth())
        self.frme_pause_0.setSizePolicy(sizePolicy)
        self.frme_pause_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_pause_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_pause_0.setObjectName("frme_pause" + suffix)
        self.layout_hrz_frme_pause_0 = QtWidgets.QHBoxLayout(self.frme_pause_0)
        self.layout_hrz_frme_pause_0.setContentsMargins(0, 3, 0, 3)
        self.layout_hrz_frme_pause_0.setSpacing(0)
        self.layout_hrz_frme_pause_0.setObjectName("layout_hrz_frme_pause" + suffix)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_hrz_frme_pause_0.addItem(spacerItem)
        self.chbx_pause_0 = QtWidgets.QCheckBox(self.frme_pause_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbx_pause_0.sizePolicy().hasHeightForWidth())
        self.chbx_pause_0.setSizePolicy(sizePolicy)
        self.chbx_pause_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chbx_pause_0.setTristate(False)
        self.chbx_pause_0.setObjectName("chbx_pause" + suffix)
        self.layout_hrz_frme_pause_0.addWidget(self.chbx_pause_0)
        spacerItem1 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_hrz_frme_pause_0.addItem(spacerItem1)
        self.layout_vrt_frme_cap_controls_0.addWidget(self.frme_pause_0)
        self.frme_rotate_image_0 = QtWidgets.QFrame(self.frme_cap_controls_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frme_rotate_image_0.sizePolicy().hasHeightForWidth())
        self.frme_rotate_image_0.setSizePolicy(sizePolicy)
        self.frme_rotate_image_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_rotate_image_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_rotate_image_0.setObjectName("frme_rotate_image" + suffix)
        self.layout_vrt_frme_rotate_image_0 = QtWidgets.QVBoxLayout(self.frme_rotate_image_0)
        self.layout_vrt_frme_rotate_image_0.setContentsMargins(0, 3, 0, 3)
        self.layout_vrt_frme_rotate_image_0.setSpacing(0)
        self.layout_vrt_frme_rotate_image_0.setObjectName("layout_vrt_frme_rotate_image" + suffix)
        self.lbl_static_rotate_0 = QtWidgets.QLabel(self.frme_rotate_image_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_static_rotate_0.sizePolicy().hasHeightForWidth())
        self.lbl_static_rotate_0.setSizePolicy(sizePolicy)
        self.lbl_static_rotate_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_static_rotate_0.setObjectName("lbl_static_rotate" + suffix)
        self.layout_vrt_frme_rotate_image_0.addWidget(self.lbl_static_rotate_0)
        self.spbx_rotate_image_0 = QtWidgets.QSpinBox(self.frme_rotate_image_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbx_rotate_image_0.sizePolicy().hasHeightForWidth())
        self.spbx_rotate_image_0.setSizePolicy(sizePolicy)
        self.spbx_rotate_image_0.setMaximum(270)
        self.spbx_rotate_image_0.setSingleStep(90)
        self.spbx_rotate_image_0.setProperty("value", 0)
        self.spbx_rotate_image_0.setObjectName("spbx_rotate_image" + suffix)
        self.layout_vrt_frme_rotate_image_0.addWidget(self.spbx_rotate_image_0)
        self.layout_vrt_frme_cap_controls_0.addWidget(self.frme_rotate_image_0)
        self.scar_cap_props_0 = QtWidgets.QScrollArea(self.frme_cap_controls_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scar_cap_props_0.sizePolicy().hasHeightForWidth())
        self.scar_cap_props_0.setSizePolicy(sizePolicy)
        self.scar_cap_props_0.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scar_cap_props_0.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scar_cap_props_0.setWidgetResizable(True)
        self.scar_cap_props_0.setObjectName("scar_cap_props" + suffix)
        self.scar_con_cap_props_0 = QtWidgets.QWidget()
        self.scar_con_cap_props_0.setGeometry(QtCore.QRect(0, 0, 59, 425))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scar_con_cap_props_0.sizePolicy().hasHeightForWidth())
        self.scar_con_cap_props_0.setSizePolicy(sizePolicy)
        self.scar_con_cap_props_0.setObjectName("scar_con_cap_props" + suffix)
        self.layout_vrt_scar_con_cap_props_0 = QtWidgets.QVBoxLayout(self.scar_con_cap_props_0)
        self.layout_vrt_scar_con_cap_props_0.setContentsMargins(0, 0, 0, 0)
        self.layout_vrt_scar_con_cap_props_0.setSpacing(0)
        self.layout_vrt_scar_con_cap_props_0.setObjectName("layout_vrt_scar_con_cap_props" + suffix)
        self.frme_cap_focus_0 = QtWidgets.QFrame(self.scar_con_cap_props_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frme_cap_focus_0.sizePolicy().hasHeightForWidth())
        self.frme_cap_focus_0.setSizePolicy(sizePolicy)
        self.frme_cap_focus_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_cap_focus_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_cap_focus_0.setObjectName("frme_cap_focus" + suffix)
        self.layout_vrt_frme_cap_brightness_1 = QtWidgets.QVBoxLayout(self.frme_cap_focus_0)
        self.layout_vrt_frme_cap_brightness_1.setContentsMargins(3, 0, 3, 0)
        self.layout_vrt_frme_cap_brightness_1.setSpacing(0)
        self.layout_vrt_frme_cap_brightness_1.setObjectName("layout_vrt_frme_cap_brightness_1")
        self.lbl_static_focus_0 = QtWidgets.QLabel(self.frme_cap_focus_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_static_focus_0.sizePolicy().hasHeightForWidth())
        self.lbl_static_focus_0.setSizePolicy(sizePolicy)
        self.lbl_static_focus_0.setObjectName("lbl_static_focus" + suffix)
        self.layout_vrt_frme_cap_brightness_1.addWidget(self.lbl_static_focus_0)
        self.spbx_cap_focus_0 = QtWidgets.QSpinBox(self.frme_cap_focus_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbx_cap_focus_0.sizePolicy().hasHeightForWidth())
        self.spbx_cap_focus_0.setSizePolicy(sizePolicy)
        self.spbx_cap_focus_0.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.spbx_cap_focus_0.setMinimum(0)
        self.spbx_cap_focus_0.setMaximum(1100)
        self.spbx_cap_focus_0.setProperty("value", 550)
        self.spbx_cap_focus_0.setObjectName("spbx_cap_focus" + suffix)
        self.layout_vrt_frme_cap_brightness_1.addWidget(self.spbx_cap_focus_0)
        self.chbx_cap_autofocus_0 = QtWidgets.QCheckBox(self.frme_cap_focus_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbx_cap_autofocus_0.sizePolicy().hasHeightForWidth())
        self.chbx_cap_autofocus_0.setSizePolicy(sizePolicy)
        self.chbx_cap_autofocus_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chbx_cap_autofocus_0.setObjectName("chbx_cap_autofocus" + suffix)
        self.layout_vrt_frme_cap_brightness_1.addWidget(self.chbx_cap_autofocus_0)
        self.layout_vrt_scar_con_cap_props_0.addWidget(self.frme_cap_focus_0)
        self.frme_cap_exposure_0 = QtWidgets.QFrame(self.scar_con_cap_props_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frme_cap_exposure_0.sizePolicy().hasHeightForWidth())
        self.frme_cap_exposure_0.setSizePolicy(sizePolicy)
        self.frme_cap_exposure_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frme_cap_exposure_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_cap_exposure_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_cap_exposure_0.setObjectName("frme_cap_exposure" + suffix)
        self.layout_vrt_frme_cap_exposure_0 = QtWidgets.QVBoxLayout(self.frme_cap_exposure_0)
        self.layout_vrt_frme_cap_exposure_0.setContentsMargins(3, 0, 3, 0)
        self.layout_vrt_frme_cap_exposure_0.setSpacing(0)
        self.layout_vrt_frme_cap_exposure_0.setObjectName("layout_vrt_frme_cap_exposure" + suffix)
        self.lbl_static_exposure_0 = QtWidgets.QLabel(self.frme_cap_exposure_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_static_exposure_0.sizePolicy().hasHeightForWidth())
        self.lbl_static_exposure_0.setSizePolicy(sizePolicy)
        self.lbl_static_exposure_0.setObjectName("lbl_static_exposure" + suffix)
        self.layout_vrt_frme_cap_exposure_0.addWidget(self.lbl_static_exposure_0)
        self.spbx_cap_exposure_0 = QtWidgets.QSpinBox(self.frme_cap_exposure_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbx_cap_exposure_0.sizePolicy().hasHeightForWidth())
        self.spbx_cap_exposure_0.setSizePolicy(sizePolicy)
        self.spbx_cap_exposure_0.setMinimum(-20)
        self.spbx_cap_exposure_0.setMaximum(20)
        self.spbx_cap_exposure_0.setProperty("value", -6)
        self.spbx_cap_exposure_0.setObjectName("spbx_cap_exposure" + suffix)
        self.layout_vrt_frme_cap_exposure_0.addWidget(self.spbx_cap_exposure_0)
        self.chbx_cap_autoexposure_0 = QtWidgets.QCheckBox(self.frme_cap_exposure_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbx_cap_autoexposure_0.sizePolicy().hasHeightForWidth())
        self.chbx_cap_autoexposure_0.setSizePolicy(sizePolicy)
        self.chbx_cap_autoexposure_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chbx_cap_autoexposure_0.setChecked(True)
        self.chbx_cap_autoexposure_0.setObjectName("chbx_cap_autoexposure" + suffix)
        self.layout_vrt_frme_cap_exposure_0.addWidget(self.chbx_cap_autoexposure_0)
        self.layout_vrt_scar_con_cap_props_0.addWidget(self.frme_cap_exposure_0)
        self.frme_cap_backlight_0 = QtWidgets.QFrame(self.scar_con_cap_props_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frme_cap_backlight_0.sizePolicy().hasHeightForWidth())
        self.frme_cap_backlight_0.setSizePolicy(sizePolicy)
        self.frme_cap_backlight_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frme_cap_backlight_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_cap_backlight_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_cap_backlight_0.setObjectName("frme_cap_backlight" + suffix)
        self.layout_vrt_frme_cap_backlight_0 = QtWidgets.QVBoxLayout(self.frme_cap_backlight_0)
        self.layout_vrt_frme_cap_backlight_0.setContentsMargins(3, 0, 3, 0)
        self.layout_vrt_frme_cap_backlight_0.setSpacing(0)
        self.layout_vrt_frme_cap_backlight_0.setObjectName("layout_vrt_frme_cap_backlight" + suffix)
        self.lbl_static_backlight_0 = QtWidgets.QLabel(self.frme_cap_backlight_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_static_backlight_0.sizePolicy().hasHeightForWidth())
        self.lbl_static_backlight_0.setSizePolicy(sizePolicy)
        self.lbl_static_backlight_0.setObjectName("lbl_static_backlight" + suffix)
        self.layout_vrt_frme_cap_backlight_0.addWidget(self.lbl_static_backlight_0)
        self.spbx_cap_backlight_0 = QtWidgets.QSpinBox(self.frme_cap_backlight_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbx_cap_backlight_0.sizePolicy().hasHeightForWidth())
        self.spbx_cap_backlight_0.setSizePolicy(sizePolicy)
        self.spbx_cap_backlight_0.setMinimum(-10)
        self.spbx_cap_backlight_0.setMaximum(10)
        self.spbx_cap_backlight_0.setProperty("value", 1)
        self.spbx_cap_backlight_0.setObjectName("spbx_cap_backlight" + suffix)
        self.layout_vrt_frme_cap_backlight_0.addWidget(self.spbx_cap_backlight_0)
        self.layout_vrt_scar_con_cap_props_0.addWidget(self.frme_cap_backlight_0)
        self.frme_cap_sharpness_0 = QtWidgets.QFrame(self.scar_con_cap_props_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frme_cap_sharpness_0.sizePolicy().hasHeightForWidth())
        self.frme_cap_sharpness_0.setSizePolicy(sizePolicy)
        self.frme_cap_sharpness_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frme_cap_sharpness_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_cap_sharpness_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_cap_sharpness_0.setObjectName("frme_cap_sharpness" + suffix)
        self.layout_vrt_frme_cap_sharpness_0 = QtWidgets.QVBoxLayout(self.frme_cap_sharpness_0)
        self.layout_vrt_frme_cap_sharpness_0.setContentsMargins(3, 0, 3, 0)
        self.layout_vrt_frme_cap_sharpness_0.setSpacing(0)
        self.layout_vrt_frme_cap_sharpness_0.setObjectName("layout_vrt_frme_cap_sharpness" + suffix)
        self.lbl_static_sharpness_0 = QtWidgets.QLabel(self.frme_cap_sharpness_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_static_sharpness_0.sizePolicy().hasHeightForWidth())
        self.lbl_static_sharpness_0.setSizePolicy(sizePolicy)
        self.lbl_static_sharpness_0.setObjectName("lbl_static_sharpness" + suffix)
        self.layout_vrt_frme_cap_sharpness_0.addWidget(self.lbl_static_sharpness_0)
        self.spbx_cap_sharpness_0 = QtWidgets.QSpinBox(self.frme_cap_sharpness_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbx_cap_sharpness_0.sizePolicy().hasHeightForWidth())
        self.spbx_cap_sharpness_0.setSizePolicy(sizePolicy)
        self.spbx_cap_sharpness_0.setMinimum(-100)
        self.spbx_cap_sharpness_0.setMaximum(100)
        self.spbx_cap_sharpness_0.setProperty("value", 3)
        self.spbx_cap_sharpness_0.setObjectName("spbx_cap_sharpness" + suffix)
        self.layout_vrt_frme_cap_sharpness_0.addWidget(self.spbx_cap_sharpness_0)
        self.layout_vrt_scar_con_cap_props_0.addWidget(self.frme_cap_sharpness_0)
        self.frme_cap_gamma_0 = QtWidgets.QFrame(self.scar_con_cap_props_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frme_cap_gamma_0.sizePolicy().hasHeightForWidth())
        self.frme_cap_gamma_0.setSizePolicy(sizePolicy)
        self.frme_cap_gamma_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frme_cap_gamma_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_cap_gamma_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_cap_gamma_0.setObjectName("frme_cap_gamma" + suffix)
        self.layout_vrt_frme_cap_gamma_0 = QtWidgets.QVBoxLayout(self.frme_cap_gamma_0)
        self.layout_vrt_frme_cap_gamma_0.setContentsMargins(3, 0, 3, 0)
        self.layout_vrt_frme_cap_gamma_0.setSpacing(0)
        self.layout_vrt_frme_cap_gamma_0.setObjectName("layout_vrt_frme_cap_gamma" + suffix)
        self.lbl_static_gamma_0 = QtWidgets.QLabel(self.frme_cap_gamma_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_static_gamma_0.sizePolicy().hasHeightForWidth())
        self.lbl_static_gamma_0.setSizePolicy(sizePolicy)
        self.lbl_static_gamma_0.setObjectName("lbl_static_gamma" + suffix)
        self.layout_vrt_frme_cap_gamma_0.addWidget(self.lbl_static_gamma_0)
        self.spbx_cap_gamma_0 = QtWidgets.QSpinBox(self.frme_cap_gamma_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbx_cap_gamma_0.sizePolicy().hasHeightForWidth())
        self.spbx_cap_gamma_0.setSizePolicy(sizePolicy)
        self.spbx_cap_gamma_0.setMaximum(1000)
        self.spbx_cap_gamma_0.setProperty("value", 100)
        self.spbx_cap_gamma_0.setObjectName("spbx_cap_gamma" + suffix)
        self.layout_vrt_frme_cap_gamma_0.addWidget(self.spbx_cap_gamma_0)
        self.layout_vrt_scar_con_cap_props_0.addWidget(self.frme_cap_gamma_0)
        self.frme_cap_gain_0 = QtWidgets.QFrame(self.scar_con_cap_props_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frme_cap_gain_0.sizePolicy().hasHeightForWidth())
        self.frme_cap_gain_0.setSizePolicy(sizePolicy)
        self.frme_cap_gain_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frme_cap_gain_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_cap_gain_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_cap_gain_0.setObjectName("frme_cap_gain" + suffix)
        self.layout_vrt_frme_cap_gain_0 = QtWidgets.QVBoxLayout(self.frme_cap_gain_0)
        self.layout_vrt_frme_cap_gain_0.setContentsMargins(3, 0, 3, 0)
        self.layout_vrt_frme_cap_gain_0.setSpacing(0)
        self.layout_vrt_frme_cap_gain_0.setObjectName("layout_vrt_frme_cap_gain" + suffix)
        self.lbl_static_gain_0 = QtWidgets.QLabel(self.frme_cap_gain_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_static_gain_0.sizePolicy().hasHeightForWidth())
        self.lbl_static_gain_0.setSizePolicy(sizePolicy)
        self.lbl_static_gain_0.setObjectName("lbl_static_gain" + suffix)
        self.layout_vrt_frme_cap_gain_0.addWidget(self.lbl_static_gain_0)
        self.spbx_cap_gain_0 = QtWidgets.QSpinBox(self.frme_cap_gain_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbx_cap_gain_0.sizePolicy().hasHeightForWidth())
        self.spbx_cap_gain_0.setSizePolicy(sizePolicy)
        self.spbx_cap_gain_0.setMaximum(1000)
        self.spbx_cap_gain_0.setProperty("value", 0)
        self.spbx_cap_gain_0.setObjectName("spbx_cap_gain" + suffix)
        self.layout_vrt_frme_cap_gain_0.addWidget(self.spbx_cap_gain_0)
        self.layout_vrt_scar_con_cap_props_0.addWidget(self.frme_cap_gain_0)
        self.frme_cap_contrast_0 = QtWidgets.QFrame(self.scar_con_cap_props_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frme_cap_contrast_0.sizePolicy().hasHeightForWidth())
        self.frme_cap_contrast_0.setSizePolicy(sizePolicy)
        self.frme_cap_contrast_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frme_cap_contrast_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_cap_contrast_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_cap_contrast_0.setObjectName("frme_cap_contrast" + suffix)
        self.layout_vrt_frme_cap_contrast_0 = QtWidgets.QVBoxLayout(self.frme_cap_contrast_0)
        self.layout_vrt_frme_cap_contrast_0.setContentsMargins(3, 0, 3, 0)
        self.layout_vrt_frme_cap_contrast_0.setSpacing(0)
        self.layout_vrt_frme_cap_contrast_0.setObjectName("layout_vrt_frme_cap_contrast" + suffix)
        self.lbl_static_contrast_0 = QtWidgets.QLabel(self.frme_cap_contrast_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_static_contrast_0.sizePolicy().hasHeightForWidth())
        self.lbl_static_contrast_0.setSizePolicy(sizePolicy)
        self.lbl_static_contrast_0.setObjectName("lbl_static_contrast" + suffix)
        self.layout_vrt_frme_cap_contrast_0.addWidget(self.lbl_static_contrast_0)
        self.spbx_cap_contrast_0 = QtWidgets.QSpinBox(self.frme_cap_contrast_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbx_cap_contrast_0.sizePolicy().hasHeightForWidth())
        self.spbx_cap_contrast_0.setSizePolicy(sizePolicy)
        self.spbx_cap_contrast_0.setMinimum(-100)
        self.spbx_cap_contrast_0.setMaximum(100)
        self.spbx_cap_contrast_0.setProperty("value", 32)
        self.spbx_cap_contrast_0.setObjectName("spbx_cap_contrast" + suffix)
        self.layout_vrt_frme_cap_contrast_0.addWidget(self.spbx_cap_contrast_0)
        self.layout_vrt_scar_con_cap_props_0.addWidget(self.frme_cap_contrast_0)
        self.frme_cap_saturation_0 = QtWidgets.QFrame(self.scar_con_cap_props_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frme_cap_saturation_0.sizePolicy().hasHeightForWidth())
        self.frme_cap_saturation_0.setSizePolicy(sizePolicy)
        self.frme_cap_saturation_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frme_cap_saturation_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_cap_saturation_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_cap_saturation_0.setObjectName("frme_cap_saturation" + suffix)
        self.layout_vrt_frme_cap_saturation_0 = QtWidgets.QVBoxLayout(self.frme_cap_saturation_0)
        self.layout_vrt_frme_cap_saturation_0.setContentsMargins(3, 0, 3, 0)
        self.layout_vrt_frme_cap_saturation_0.setSpacing(0)
        self.layout_vrt_frme_cap_saturation_0.setObjectName("layout_vrt_frme_cap_saturation" + suffix)
        self.lbl_static_saturation_0 = QtWidgets.QLabel(self.frme_cap_saturation_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_static_saturation_0.sizePolicy().hasHeightForWidth())
        self.lbl_static_saturation_0.setSizePolicy(sizePolicy)
        self.lbl_static_saturation_0.setObjectName("lbl_static_saturation" + suffix)
        self.layout_vrt_frme_cap_saturation_0.addWidget(self.lbl_static_saturation_0)
        self.spbx_cap_saturation_0 = QtWidgets.QSpinBox(self.frme_cap_saturation_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbx_cap_saturation_0.sizePolicy().hasHeightForWidth())
        self.spbx_cap_saturation_0.setSizePolicy(sizePolicy)
        self.spbx_cap_saturation_0.setMinimum(-200)
        self.spbx_cap_saturation_0.setMaximum(200)
        self.spbx_cap_saturation_0.setProperty("value", 64)
        self.spbx_cap_saturation_0.setObjectName("spbx_cap_saturation" + suffix)
        self.layout_vrt_frme_cap_saturation_0.addWidget(self.spbx_cap_saturation_0)
        self.layout_vrt_scar_con_cap_props_0.addWidget(self.frme_cap_saturation_0)
        self.frme_cap_brightness_0 = QtWidgets.QFrame(self.scar_con_cap_props_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frme_cap_brightness_0.sizePolicy().hasHeightForWidth())
        self.frme_cap_brightness_0.setSizePolicy(sizePolicy)
        self.frme_cap_brightness_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_cap_brightness_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_cap_brightness_0.setObjectName("frme_cap_brightness" + suffix)
        self.layout_vrt_frme_cap_brightness_0 = QtWidgets.QVBoxLayout(self.frme_cap_brightness_0)
        self.layout_vrt_frme_cap_brightness_0.setContentsMargins(3, 0, 3, 0)
        self.layout_vrt_frme_cap_brightness_0.setSpacing(0)
        self.layout_vrt_frme_cap_brightness_0.setObjectName("layout_vrt_frme_cap_brightness" + suffix)
        self.lbl_static_brightness_0 = QtWidgets.QLabel(self.frme_cap_brightness_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_static_brightness_0.sizePolicy().hasHeightForWidth())
        self.lbl_static_brightness_0.setSizePolicy(sizePolicy)
        self.lbl_static_brightness_0.setObjectName("lbl_static_brightness" + suffix)
        self.layout_vrt_frme_cap_brightness_0.addWidget(self.lbl_static_brightness_0)
        self.spbx_cap_brightness_0 = QtWidgets.QSpinBox(self.frme_cap_brightness_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbx_cap_brightness_0.sizePolicy().hasHeightForWidth())
        self.spbx_cap_brightness_0.setSizePolicy(sizePolicy)
        self.spbx_cap_brightness_0.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.spbx_cap_brightness_0.setMinimum(-100)
        self.spbx_cap_brightness_0.setMaximum(100)
        self.spbx_cap_brightness_0.setProperty("value", 0)
        self.spbx_cap_brightness_0.setObjectName("spbx_cap_brightness" + suffix)
        self.layout_vrt_frme_cap_brightness_0.addWidget(self.spbx_cap_brightness_0)
        self.layout_vrt_scar_con_cap_props_0.addWidget(self.frme_cap_brightness_0)
        self.frme_cap_hue_0 = QtWidgets.QFrame(self.scar_con_cap_props_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frme_cap_hue_0.sizePolicy().hasHeightForWidth())
        self.frme_cap_hue_0.setSizePolicy(sizePolicy)
        self.frme_cap_hue_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frme_cap_hue_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_cap_hue_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_cap_hue_0.setObjectName("frme_cap_hue" + suffix)
        self.layout_vrt_frme_cap_hue_0 = QtWidgets.QVBoxLayout(self.frme_cap_hue_0)
        self.layout_vrt_frme_cap_hue_0.setContentsMargins(3, 0, 3, 0)
        self.layout_vrt_frme_cap_hue_0.setSpacing(0)
        self.layout_vrt_frme_cap_hue_0.setObjectName("layout_vrt_frme_cap_hue" + suffix)
        self.lbl_static_hue_0 = QtWidgets.QLabel(self.frme_cap_hue_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_static_hue_0.sizePolicy().hasHeightForWidth())
        self.lbl_static_hue_0.setSizePolicy(sizePolicy)
        self.lbl_static_hue_0.setObjectName("lbl_static_hue" + suffix)
        self.layout_vrt_frme_cap_hue_0.addWidget(self.lbl_static_hue_0)
        self.spbx_cap_hue_0 = QtWidgets.QSpinBox(self.frme_cap_hue_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbx_cap_hue_0.sizePolicy().hasHeightForWidth())
        self.spbx_cap_hue_0.setSizePolicy(sizePolicy)
        self.spbx_cap_hue_0.setMinimum(-100)
        self.spbx_cap_hue_0.setMaximum(100)
        self.spbx_cap_hue_0.setProperty("value", 0)
        self.spbx_cap_hue_0.setObjectName("spbx_cap_hue" + suffix)
        self.layout_vrt_frme_cap_hue_0.addWidget(self.spbx_cap_hue_0)
        self.layout_vrt_scar_con_cap_props_0.addWidget(self.frme_cap_hue_0)
        self.frme_cap_white_0 = QtWidgets.QFrame(self.scar_con_cap_props_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frme_cap_white_0.sizePolicy().hasHeightForWidth())
        self.frme_cap_white_0.setSizePolicy(sizePolicy)
        self.frme_cap_white_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frme_cap_white_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_cap_white_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_cap_white_0.setObjectName("frme_cap_white" + suffix)
        self.layout_vrt_frme_cap_white_0 = QtWidgets.QVBoxLayout(self.frme_cap_white_0)
        self.layout_vrt_frme_cap_white_0.setContentsMargins(3, 0, 3, 0)
        self.layout_vrt_frme_cap_white_0.setSpacing(0)
        self.layout_vrt_frme_cap_white_0.setObjectName("layout_vrt_frme_cap_white" + suffix)
        self.lbl_static_white_0 = QtWidgets.QLabel(self.frme_cap_white_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_static_white_0.sizePolicy().hasHeightForWidth())
        self.lbl_static_white_0.setSizePolicy(sizePolicy)
        self.lbl_static_white_0.setObjectName("lbl_static_white" + suffix)
        self.layout_vrt_frme_cap_white_0.addWidget(self.lbl_static_white_0)
        self.spbx_cap_white_0 = QtWidgets.QSpinBox(self.frme_cap_white_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbx_cap_white_0.sizePolicy().hasHeightForWidth())
        self.spbx_cap_white_0.setSizePolicy(sizePolicy)
        self.spbx_cap_white_0.setMaximum(10000)
        self.spbx_cap_white_0.setSingleStep(10)
        self.spbx_cap_white_0.setProperty("value", 4600)
        self.spbx_cap_white_0.setObjectName("spbx_cap_white" + suffix)
        self.layout_vrt_frme_cap_white_0.addWidget(self.spbx_cap_white_0)
        self.chbx_cap_autowhite_0 = QtWidgets.QCheckBox(self.frme_cap_white_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbx_cap_autowhite_0.sizePolicy().hasHeightForWidth())
        self.chbx_cap_autowhite_0.setSizePolicy(sizePolicy)
        self.chbx_cap_autowhite_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chbx_cap_autowhite_0.setChecked(True)
        self.chbx_cap_autowhite_0.setObjectName("chbx_cap_autowhite" + suffix)
        self.layout_vrt_frme_cap_white_0.addWidget(self.chbx_cap_autowhite_0)
        self.layout_vrt_scar_con_cap_props_0.addWidget(self.frme_cap_white_0)
        self.scar_cap_props_0.setWidget(self.scar_con_cap_props_0)
        self.layout_vrt_frme_cap_controls_0.addWidget(self.scar_cap_props_0)
        self.frme_cap_resolution_0 = QtWidgets.QFrame(self.frme_cap_controls_0)
        self.frme_cap_resolution_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_cap_resolution_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_cap_resolution_0.setObjectName("frme_cap_resolution" + suffix)
        self.layout_grid_frme_cap_res_0 = QtWidgets.QGridLayout(self.frme_cap_resolution_0)
        self.layout_grid_frme_cap_res_0.setContentsMargins(3, 0, 3, 1)
        self.layout_grid_frme_cap_res_0.setSpacing(0)
        self.layout_grid_frme_cap_res_0.setObjectName("layout_grid_frme_cap_res" + suffix)
        self.lbl_static_resolution_0 = QtWidgets.QLabel(self.frme_cap_resolution_0)
        self.lbl_static_resolution_0.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_static_resolution_0.setObjectName("lbl_static_resolution" + suffix)
        self.layout_grid_frme_cap_res_0.addWidget(self.lbl_static_resolution_0, 0, 1, 1, 1)
        self.lbl_static_w_resolution_0 = QtWidgets.QLabel(self.frme_cap_resolution_0)
        self.lbl_static_w_resolution_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_static_w_resolution_0.setObjectName("lbl_static_w_resolution" + suffix)
        self.layout_grid_frme_cap_res_0.addWidget(self.lbl_static_w_resolution_0, 1, 0, 1, 1)
        self.ledit_cap_width_0 = QtWidgets.QLineEdit(self.frme_cap_resolution_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledit_cap_width_0.sizePolicy().hasHeightForWidth())
        self.ledit_cap_width_0.setSizePolicy(sizePolicy)
        self.ledit_cap_width_0.setReadOnly(True)
        self.ledit_cap_width_0.setObjectName("ledit_cap_width" + suffix)
        self.layout_grid_frme_cap_res_0.addWidget(self.ledit_cap_width_0, 1, 1, 1, 1)
        self.lbl_static_h_resolution_0 = QtWidgets.QLabel(self.frme_cap_resolution_0)
        self.lbl_static_h_resolution_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_static_h_resolution_0.setObjectName("lbl_static_h_resolution" + suffix)
        self.layout_grid_frme_cap_res_0.addWidget(self.lbl_static_h_resolution_0, 2, 0, 1, 1)
        self.ledit_cap_height_0 = QtWidgets.QLineEdit(self.frme_cap_resolution_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledit_cap_height_0.sizePolicy().hasHeightForWidth())
        self.ledit_cap_height_0.setSizePolicy(sizePolicy)
        self.ledit_cap_height_0.setReadOnly(True)
        self.ledit_cap_height_0.setObjectName("ledit_cap_height" + suffix)
        self.layout_grid_frme_cap_res_0.addWidget(self.ledit_cap_height_0, 2, 1, 1, 1)
        self.lbl_static_c_resolution_0 = QtWidgets.QLabel(self.frme_cap_resolution_0)
        self.lbl_static_c_resolution_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_static_c_resolution_0.setObjectName("lbl_static_c_resolution" + suffix)
        self.layout_grid_frme_cap_res_0.addWidget(self.lbl_static_c_resolution_0, 3, 0, 1, 1)
        self.ledit_cap_channels_0 = QtWidgets.QLineEdit(self.frme_cap_resolution_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledit_cap_channels_0.sizePolicy().hasHeightForWidth())
        self.ledit_cap_channels_0.setSizePolicy(sizePolicy)
        self.ledit_cap_channels_0.setText("")
        self.ledit_cap_channels_0.setReadOnly(True)
        self.ledit_cap_channels_0.setObjectName("ledit_cap_channels" + suffix)
        self.layout_grid_frme_cap_res_0.addWidget(self.ledit_cap_channels_0, 3, 1, 1, 1)
        self.layout_vrt_frme_cap_controls_0.addWidget(self.frme_cap_resolution_0)
        self.frme_cam_index_0 = QtWidgets.QFrame(self.frme_cap_controls_0)
        self.frme_cam_index_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_cam_index_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_cam_index_0.setObjectName("frme_cam_index" + suffix)
        self.layout_hrz_cam_index_0 = QtWidgets.QHBoxLayout(self.frme_cam_index_0)
        self.layout_hrz_cam_index_0.setContentsMargins(1, 0, 0, 0)
        self.layout_hrz_cam_index_0.setSpacing(0)
        self.layout_hrz_cam_index_0.setObjectName("layout_hrz_cam_index" + suffix)
        self.lbl_static_cam_index_0 = QtWidgets.QLabel(self.frme_cam_index_0)
        self.lbl_static_cam_index_0.setObjectName("lbl_static_cam_index" + suffix)
        self.layout_hrz_cam_index_0.addWidget(self.lbl_static_cam_index_0)
        self.ledit_cam_index_0 = QtWidgets.QLineEdit(self.frme_cam_index_0)
        self.ledit_cam_index_0.setMaximumSize(QtCore.QSize(20, 16777215))
        self.ledit_cam_index_0.setObjectName("ledit_cam_index" + suffix)
        self.layout_hrz_cam_index_0.addWidget(self.ledit_cam_index_0)
        self.layout_vrt_frme_cap_controls_0.addWidget(self.frme_cam_index_0)
        self.layout_hrz_frme_cap_panel_0.addWidget(self.frme_cap_controls_0)
        self.frme_cap_display_0 = QtWidgets.QFrame(self.frme_cap_panel_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frme_cap_display_0.sizePolicy().hasHeightForWidth())
        self.frme_cap_display_0.setSizePolicy(sizePolicy)
        self.frme_cap_display_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frme_cap_display_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frme_cap_display_0.setObjectName("frme_cap_display" + suffix)
        self.layout_grid_frme_cap_display_0 = QtWidgets.QGridLayout(self.frme_cap_display_0)
        self.layout_grid_frme_cap_display_0.setContentsMargins(0, 0, 0, 0)
        self.layout_grid_frme_cap_display_0.setSpacing(0)
        self.layout_grid_frme_cap_display_0.setObjectName("layout_grid_frme_cap_display" + suffix)
        self.lbl_cap_display_pixmap_0 = QtWidgets.QLabel(self.frme_cap_display_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_cap_display_pixmap_0.sizePolicy().hasHeightForWidth())
        self.lbl_cap_display_pixmap_0.setSizePolicy(sizePolicy)
        self.lbl_cap_display_pixmap_0.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lbl_cap_display_pixmap_0.setFrameShape(QtWidgets.QFrame.Panel)
        self.lbl_cap_display_pixmap_0.setText("")
        self.lbl_cap_display_pixmap_0.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.lbl_cap_display_pixmap_0.setObjectName("lbl_cap_display_pixmap" + suffix)
        self.layout_grid_frme_cap_display_0.addWidget(self.lbl_cap_display_pixmap_0, 0, 0, 1, 1)
        self.sbar_vrt_cap_display_0 = QtWidgets.QScrollBar(self.frme_cap_display_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbar_vrt_cap_display_0.sizePolicy().hasHeightForWidth())
        self.sbar_vrt_cap_display_0.setSizePolicy(sizePolicy)
        self.sbar_vrt_cap_display_0.setMaximumSize(QtCore.QSize(15, 16777215))
        self.sbar_vrt_cap_display_0.setOrientation(QtCore.Qt.Vertical)
        self.sbar_vrt_cap_display_0.setObjectName("sbar_vrt_cap_display" + suffix)
        self.layout_grid_frme_cap_display_0.addWidget(self.sbar_vrt_cap_display_0, 0, 1, 1, 1)
        self.sbar_hrz_cap_display_0 = QtWidgets.QScrollBar(self.frme_cap_display_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbar_hrz_cap_display_0.sizePolicy().hasHeightForWidth())
        self.sbar_hrz_cap_display_0.setSizePolicy(sizePolicy)
        self.sbar_hrz_cap_display_0.setMaximumSize(QtCore.QSize(16777215, 15))
        self.sbar_hrz_cap_display_0.setOrientation(QtCore.Qt.Horizontal)
        self.sbar_hrz_cap_display_0.setObjectName("sbar_hrz_cap_display" + suffix)
        self.layout_grid_frme_cap_display_0.addWidget(self.sbar_hrz_cap_display_0, 1, 0, 1, 1)
        self.layout_hrz_frme_cap_panel_0.addWidget(self.frme_cap_display_0)
        self.layout_grid_frme_cap_panels.addWidget(self.frme_cap_panel_0, 0, 0, 1, 1)

        blank_img = numpy.zeros((500, 500, 1), numpy.int)
        blank_qimg = QtGui.QImage(blank_img.data, blank_img.shape[1], blank_img.shape[0], blank_img.strides[0],
                                  QtGui.QImage.Format_RGB888)
        blank_qpix = QtGui.QPixmap.fromImage(blank_qimg)
        self.lbl_cap_display_pixmap_0.setPixmap(blank_qpix)

        if space_available:
            qframe.layout().addWidget(self.frme_capture_panel, row, col, 1, 1)
        else:
            print('Max number of capture display panels reached.')

        self._set_text()

    def _set_text(self):
        self.lbl_static_zoom_0.setText("Zoom")
        self.chbx_pause_0.setText("Pause")
        self.lbl_rotate_image_0.setText("Rotate (90)")
        self.lbl_static_focus_0.setText("Focus")
        self.chbx_cap_autofocus_0.setText("Auto")
        self.lbl_static_exposure_0.setText("Exposure")
        self.chbx_cap_autoexposure_0.setText("Auto")
        self.lbl_static_backlight_0.setText("Backlight")
        self.lbl_static_sharpness_0.setText("Sharpness")
        self.lbl_static_gamma_0.setText("Gamma")
        self.lbl_static_gain_0.setText("Gain")
        self.lbl_static_contrast_0.setText("Contrast")
        self.lbl_static_saturation_0.setText("Saturation")
        self.lbl_static_brightness_0.setText("Brightness")
        self.lbl_static_hue_0.setText("Hue")
        self.lbl_static_white_0.setText("White Bal.")
        self.chbx_cap_autowhite_0.setText("Auto")
        self.lbl_static_resolution_0.setText("Resolution")
        self.lbl_static_w_resolution_0.setText("W")
        self.ledit_cap_width_0.setText("5000")
        self.lbl_static_h_resolution_0.setText("H")
        self.ledit_cap_height_0.setText("4000")
        self.lbl_static_c_resolution_0.setText("C")
        self.lbl_static_cam_index_0.setText("Cam Index")

    @staticmethod
    def _get_row_col(qframe):
        i = qframe.layout().count()
        space_available = True
        if i == 0:
            row = 0
            col = 0
        elif i == 1:
            row = 1
            col = 0
        elif i == 2:
            row = 0
            col = 1
        elif i == 3:
            row = 1
            col = 1
        else:
            row = 2
            col = 2
            space_available = False
        return row, col, space_available
